services:
  - type: web
    name: fastvidssaverbot
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_ID
        sync: false
      - key: FSUB_CHANNEL
        sync: false
      - key: CHANNEL_URL
        sync: false
      - key: OWNER_USERNAME
        sync: false
